Repository afasii-dev/java-universe-tech, pull requests merged in 2022-04, with the labels that each got.

#72 [Rustam] - HW: Game Store
  src/main/Array_string.java
  src/main/GameStore.java
Labels: invalid

#82 Lesson - abstract class and array of objects
  src/main/arrays/objectsArray/Test.java
  src/main/oop/abstractClass/Animal.java
  src/main/oop/abstractClass/Cat.java
  src/main/oop/abstractClass/Dog.java
  src/main/oop/abstractClass/Test.java
Labels: homework

#85 [Zarif] - HW: Abstract Calss
  src/Main.java
  src/Methods.java
  src/main/arrays/objectArrays/Test.java
  src/main/oop/abstractClass/Car.java
  src/main/oop/abstractClass/Truck.java
  src/main/oop/abstractClass/Van.java
  src/main/oop/abstractClass/Vehicle.java
Labels: ready to check
